## Numpy

Импортировать NumPy под именем np

In [ ]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [5]:
a = np.zeros((1, 10))
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Создать вектор размера 10, заполненный единицами

In [6]:
a = np.ones((1, 10))
print(a)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


Создать вектор размера 10, заполненный числом 2.5

In [7]:
a = np.full((1, 10), 2.5, dtype=float)
print(a)

[[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [3]:
a = np.zeros((1, 10))
a[0][5] = 1
print(a)

[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]


Развернуть вектор (первый становится последним)

In [9]:
a = np.arange(10)
print(a)
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [10]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [12]:
a = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(a))

(array([0, 1, 4]),)


Создать 3x3 единичную матрицу

In [13]:
a = np.zeros((3, 9))
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Создать массив 3x3x3 со случайными значениями

In [14]:
a = np.random.rand(3, 3, 3)
print(a)

[[[ 0.87283602  0.42109275  0.57433051]
  [ 0.73853605  0.56288155  0.07565394]
  [ 0.58947189  0.51900692  0.84270836]]

 [[ 0.27617211  0.48963498  0.30295271]
  [ 0.14551452  0.75968599  0.91789124]
  [ 0.95127445  0.7831737   0.57760502]]

 [[ 0.48068125  0.89426391  0.41636285]
  [ 0.05425686  0.02636305  0.4902538 ]
  [ 0.0832907   0.02563887  0.29572431]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [16]:
a = np.random.rand(1,30)
print(a)
print(np.average(a))

[[ 0.30552721  0.48914847  0.92773522  0.91369698  0.67295923  0.24436749
   0.45823916  0.44979867  0.0254749   0.16432509  0.75156683  0.18673971
   0.25417961  0.18223197  0.87156909  0.8014803   0.19988774  0.41935008
   0.30848916  0.4804537   0.99370635  0.93484371  0.62498995  0.45545434
   0.38752885  0.84539647  0.60611554  0.73355852  0.47728382  0.2395661 ]]
0.513522142444


Перемножить матрицы 5x3 и 3x2

In [18]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
print(a)
print(b)
print(np.dot(a, b))

[[ 0.89791474  0.96000798  0.33690812]
 [ 0.41233993  0.71709604  0.74611926]
 [ 0.65533603  0.72322381  0.56714113]
 [ 0.37544263  0.41609465  0.10360136]
 [ 0.13038859  0.45430697  0.0918051 ]]
[[ 0.13286862  0.54183146]
 [ 0.8610713   0.00722856]
 [ 0.08621172  0.82052985]]
[[ 0.97498544  0.76990111]
 [ 0.73658208  0.84081544]
 [ 0.75871507  0.82566577]
 [ 0.41710336  0.29144241]
 [ 0.41642992  0.14926146]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [19]:
a = np.arange(0.1, 1, 0.09)
print(a)

[ 0.1   0.19  0.28  0.37  0.46  0.55  0.64  0.73  0.82  0.91]


Заменить максимальный элемент на ноль

In [21]:
a = np.array([1, 2, 12, 7, 3, 4])
a[np.argmax(a)] = 0
print(a)

[1 2 0 7 3 4]


Преобразовать массив из float в int

In [24]:
a = np.array([1.2, 2.3, 12.8, 7.0, 3.2, 4.2])
a = a.astype(int)
print(a)

[ 1  2 12  7  3  4]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [32]:
from scipy.spatial import distance
a = np.random.rand(10,2)
d = distance.cdist(a, a, 'euclidean')
print(d)

[[ 0.          0.21119052  0.64088537  0.25480442  0.44012379  0.63905829
   0.69384228  0.40683502  0.84457107  0.17317558]
 [ 0.21119052  0.          0.52261699  0.3442686   0.5494622   0.6751576
   0.53616859  0.39093566  0.65746858  0.10192988]
 [ 0.64088537  0.52261699  0.          0.50332689  0.58507765  0.46816726
   0.15104475  0.30926397  0.36328973  0.48054464]
 [ 0.25480442  0.3442686   0.50332689  0.          0.20543078  0.38538524
   0.60473328  0.20355016  0.79745206  0.24340865]
 [ 0.44012379  0.5494622   0.58507765  0.20543078  0.          0.26743595
   0.71540291  0.28776454  0.92408378  0.4481457 ]
 [ 0.63905829  0.6751576   0.46816726  0.38538524  0.26743595  0.
   0.61827338  0.2924441   0.83145606  0.57825138]
 [ 0.69384228  0.53616859  0.15104475  0.60473328  0.71540291  0.61827338
   0.          0.42957318  0.21426003  0.5223278 ]
 [ 0.40683502  0.39093566  0.30926397  0.20355016  0.28776454  0.2924441
   0.42957318  0.          0.63650769  0.30102628]
 [ 0.84457

Случайно расположить p элементов в 2D массив

In [35]:
n = 10
p = 3
a = np.zeros((n,n))
print(a)
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [48]:
a = np.arange(1, 6)
print(a)
zeros = 3
result = np.zeros(len(a) + (len(a) - 1) * zeros)
result[::zeros + 1] = a
print(result)

[1 2 3 4 5]
[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

In [52]:
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)
print(np.argmax(counts))

1


Найти n наибольших значений в массиве

In [64]:
n = 5
a = np.array([4,2,3,1,4,1,1,4,3,4,2,1])
print(np.argpartition(a, -n)[-n:])

[8 7 4 9 0]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [18]:
import pandas
food = pandas.read_csv('en.openfoodfacts.org.products.tsv', error_bad_lines=False, dtype='unicode', delimiter='\t')

Посмотреть первые 5 записей

In [19]:
food.head

<bound method NDFrame.head of                  code                                                url  \
0       0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1       0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2       0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3       0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4       0000000016094  http://world-en.openfoodfacts.org/product/0000...   
5       0000000016100  http://world-en.openfoodfacts.org/product/0000...   
6       0000000016117  http://world-en.openfoodfacts.org/product/0000...   
7       0000000016124  http://world-en.openfoodfacts.org/product/0000...   
8       0000000016193  http://world-en.openfoodfacts.org/product/0000...   
9       0000000016513  http://world-en.openfoodfacts.org/product/0000...   
10      0000000016612  http://world-en.openfoodfacts.org/product/0000...   
11      0000000016650  http://world-en.openfoodfacts.org/p

Сколько наблюдений в наборе данных?


In [21]:
print(len(food))

356027


Сколько столбцов в наборе данных?

In [22]:
print(len(food.columns))

163


Напечатайте все названия столбцов

In [23]:
print(food.columns.values)

['code' 'url' 'creator' 'created_t' 'created_datetime' 'last_modified_t'
 'last_modified_datetime' 'product_name' 'generic_name' 'quantity'
 'packaging' 'packaging_tags' 'brands' 'brands_tags' 'categories'
 'categories_tags' 'categories_en' 'origins' 'origins_tags'
 'manufacturing_places' 'manufacturing_places_tags' 'labels' 'labels_tags'
 'labels_en' 'emb_codes' 'emb_codes_tags' 'first_packaging_code_geo'
 'cities' 'cities_tags' 'purchase_places' 'stores' 'countries'
 'countries_tags' 'countries_en' 'ingredients_text' 'allergens'
 'allergens_en' 'traces' 'traces_tags' 'traces_en' 'serving_size'
 'no_nutriments' 'additives_n' 'additives' 'additives_tags' 'additives_en'
 'ingredients_from_palm_oil_n' 'ingredients_from_palm_oil'
 'ingredients_from_palm_oil_tags'
 'ingredients_that_may_be_from_palm_oil_n'
 'ingredients_that_may_be_from_palm_oil'
 'ingredients_that_may_be_from_palm_oil_tags' 'nutrition_grade_uk'
 'nutrition_grade_fr' 'pnns_groups_1' 'pnns_groups_2' 'states'
 'states_tags' 

Какое название у 105 столбца?

In [31]:
food_value = food.columns[105]
print(food_value)

-fructose_100g


Какой тип наблюдений в 105 столбце?

In [30]:
print(type(food_value))

<class 'str'>


Как проиндексирован набор данных?

In [32]:
print(food.index.values)

[     0      1      2 ... 356024 356025 356026]


Каково значение имени продукта в 19-м наблюдении?

In [33]:
print(food.iloc[19]['product_name'])

Organic Oat Groats


## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [91]:
chipo = pandas.read_csv('chipotle.tsv', error_bad_lines=False, sep='\t')

Как много продуктов стоят более чем $10.00?

In [92]:

item_price_without_currency = chipo['item_price']
item_price_without_currency = item_price_without_currency.replace('[\$,]', '', regex=True).astype(float)
print(len(item_price_without_currency[item_price_without_currency.apply(lambda x: x > 10.00)]))

1130


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [81]:
print(chipo[['item_name','item_price']])

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito     

Отсортировать по имени предмета

In [93]:
print(chipo.sort_values(by='item_name'))

      order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      166

Сколько было заказано самого дорогого предмета?

In [106]:
chipo_without_currency = chipo
chipo_without_currency['item_price'] = chipo_without_currency['item_price'].replace('[\$,]', '', regex=True).astype(float)
max_value = chipo_without_currency.loc[chipo_without_currency['item_price'].idxmax()]['item_price']
print(len(chipo_without_currency[chipo_without_currency['item_price'].apply(lambda x: x == max_value)]))

44.25
1


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [107]:
print(len(chipo[chipo['item_name'].apply(lambda x: x == 'Veggie Salad Bowl')]))

18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [116]:
print(len(chipo.loc[lambda x: (x['item_name'] == 'Canned Soda') & (x['quantity'] > 1)]))

20
